casaorganica/urls.py
from django.conf import settings
from django.conf.urls import url, include, patterns
from django.conf.urls.i18n import urlpatterns
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from web import views

urlpatterns = [
    url(r'^web/', include('web.urls')),
    url(r'^loginuser$', views.login_user, name='login_user'),
    url(r'^logout$', views.logout_user, name='logout_user'),
    url(r'^aceptarOferta$', views.aceptarOferta, name='aceptarOferta'),
    url(r'^rechazarOferta$', views.rechazarOferta, name='rechazarOferta'),
    url(r'^home', views.home, name='login_user'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index, name='index'),

    url(r'^login$', views.login_user_rest, name='login_user_rest'),
    url(r'^products$', views.oferta_semana_list_rest, name='oferta_semana_list'),
    url(r'^cart/add', views.carrito_add_rest, name='carrito_add_rest'),
    url(r'^order', views.carrito_items_rest, name='carrito_items_rest'),
    url(r'^cart/checkout', views.carrito_checkout_rest, name='carrito_checkout_rest'),
    url(r'^order/schedule', views.order_schedule_rest, name='order_schedule_rest'),

]

urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
 )

urlpatterns += patterns('',
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.STATIC_ROOT,
    }),
 )

web/urls.py
from django.conf import settings
from django.conf.urls import url, include, patterns
from django.conf.urls.i18n import urlpatterns
from django.contrib import admin
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index$', views.login_user, name='login_user'),
    url(r'^home', views.index, name='index'),
    url(r'^logout$', views.logout_user, name='logout_user'),
    url(r'^Productor/home$', views.home, name='login_user'),
    url(r'^Administrador/homeAdmin$', views.homeAdmin, name='login_user'),
    url(r'^registroConsumidor', views.registroConsumidor, name='registroConsumidor'),
    url(r'^registroProductor', views.registroProductor, name='registroProductor'),
    url(r'^$', views.index, name='index'),
    url(r'^Producto/listProducts$', views.consultaProductos, name='consultaProductos'),
    url(r'^Productor/ofertaproducto/(?P<id>[0-9]+)/$', views.ofertarProducto, name='ofertarProducto'),
    url(r'^Productor/ofertaproductos/(?P<page>[0-9]+)/$', views.ofertaProductos, name='ofertaProducto'),
    url(r'^quienes$', views.quienes, name='quienes'),
    url(r'^carrito$', views.carrito, name='carrito'),
    url(r'^web/carrito$', views.carrito, name='carrito'),
    url(r'^checkout$', views.checkout, name='checkout'),
    url(r'^web/checkout$', views.checkout, name='checkout'),
    url(r'^nuestros$', views.nuestros, name='nuestros'),
    url(r'^Productor/productos$', views.productosOferta, name='productosProductor'),
    url(r'^Productor/oferta/(?P<id>[0-9]+)/$', views.ofertaProducto, name='ofertaProductor'),
    url(r'^Productor/ofertacancelar/$', views.ofertaProductoCancelar, name='ofertaProductoCancelar'),
    url(r'^Consumidor/edit$', views.consumidorEdit, name='consumidorEdit'),
    url(r'^Productor/pedidos/(?P<page>[0-9]+)/$', views.consultaPedidos, name='ofertaProducto'),

    url(r'^rest/oferta/$', views.oferta_list, name='oferta_list'),
    url(r'^rest/ofertas/(?P<pk>[0-9]+)$', views.oferta_detail, name='oferta_detail'),
    url(r'^rest/producto/$', views.producto_list, name='producto_list'),
    url(r'^rest/productos/(?P<pk>[0-9]+)$', views.producto_detail, name='producto_detail'),
    url(r'^rest/productor/$', views.productor_list, name='productor_list'),
    url(r'^rest/productores/(?P<pk>[0-9]+)$', views.productor_detail, name='productor_detail'),
    url(r'^rest/horarios/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d+)/$', views.horarios_list, name='oferta_list')
]

web/models.py
from __future__ import unicode_literals

from datetime import datetime

from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User

# Create your models here.

class Administrador(models.Model):
    nombres = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=100)
    telefono = models.CharField(max_length=100)
    correo = models.EmailField()
    usuario = models.ForeignKey(User, null=False)

    def __unicode__(self):
        return self.nombres + ' ' + self.apellidos

class Unidad(models.Model):
    nombre = models.CharField(max_length=200)

    def __unicode__(self):
        return self.nombre

class TipoProducto(models.Model):
    nombre = models.CharField(max_length=200)

    def __unicode__(self):
        return self.nombre

class Producto(models.Model):
    nombres = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=500)
    foto = models.ImageField(upload_to="casaorganica/images")
    precio = models.IntegerField(default=0)
    unidad = models.ForeignKey(Unidad, on_delete=models.CASCADE)
    tipoProducto = models.ForeignKey(TipoProducto, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.nombres


class Ciudad(models.Model):
    nombre = models.CharField(max_length=200)

    def __unicode__(self):
        return self.nombre
class Productor(models.Model):
    nombres = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=100)
    telefono = models.CharField(max_length=100)
    correo = models.EmailField()
    direccion = models.CharField(max_length=100)
    ciudad = models.ForeignKey(Ciudad, on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, null=False)

    def __unicode__(self):
        return self.nombres + ' ' + self.apellidos





class Consumidor(models.Model):
    nombres = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=100)
    correo = models.EmailField()
    direccion = models.CharField(max_length=100)
    ciudad = models.ForeignKey(Ciudad, on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, null=False)

    def __unicode__(self):
        return self.nombres + ' ' + self.apellidos

class OfertaProducto(models.Model):
    cantidad = models.IntegerField(default=0)
    precio = models.DecimalField(decimal_places=2, max_digits=12)
    producto = models.ForeignKey(Producto, null=False)
    productor = models.ForeignKey(Productor, on_delete=models.CASCADE)
    fechaOferta = models.DateTimeField(default=datetime.now)


    @property
    def costo_total(self):
        return self.cantidad * self.precio

class MedioPago(models.Model):
    nombre = models.CharField(max_length=200)

    def __unicode__(self):
        return self.nombre

class CarritoItem(models.Model):
    cantidad = models.IntegerField(default=0)
    producto = models.ForeignKey(OfertaProducto, null=False)
    precio = models.FloatField(default=0)

class Carrito(models.Model):
    items = models.ManyToManyField(CarritoItem)
    comprador = models.ForeignKey(Consumidor, null=False)
    total = models.IntegerField(default=0)
    activo = models.BooleanField(default=False, null=False)

class HorarioDistribucion(models.Model):
    dia = models.DateField(null=False)
    horaInicio = models.TimeField(null=False)
    horaFin = models.TimeField(null=False)

class OrdenCompra(models.Model):
    carrito = models.ForeignKey(Carrito, null=False)
    fechaCompra = models.DateTimeField(default=datetime.now)
    horarioDistribucion = models.ForeignKey(HorarioDistribucion, null=True)

class ProductoForm(ModelForm):

    class Meta:
        model=Producto
        fields=['nombres', 'descripcion', 'foto', 'precio', 'unidad','tipoProducto']

class BusquedaForm(ModelForm):

    class Meta:
        model=Producto
        fields=['precio','tipoProducto']

web/templates/web/base.html
<!DOCTYPE html>
{% load bootstrap_themes %}
{% load bootstrap3 %}
{% load static %}
{% load staticfiles %}
{# Cargar CSS y JavaScript#}
{% bootstrap_javascript jquery=1 %}
{% bootstrap_styles theme='flatly' type='min.css' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Casa Organica</title>
    <!-- Custom CSS -->
    <link href="../static/css/thumbnail1-gallery.css" rel="stylesheet">
</head>
<body>
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
        <a href="/" class="navbar-brand">Casa Organica</a>
        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar-main">
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li><a href="/logout" class="navbar-brand">Cerrar Sesion</a></li>
            {% else %}
            <li><a href="/login" class="navbar-brand">Iniciar Sesion</a></li>
            {% endif %}
        </ul>
    </div>
  </div>
</div>
<br/>
<br/>
<br/>
<div class="container">
    {% if messages %}
        {% for message in messages %}
            <div>{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

web/templates/web/login.html
<!DOCTYPE html>

{#% extends 'web/base.html' %#}
{% load bootstrap_themes %}
{% load bootstrap3 %}
{% load static %}
{% load staticfiles %}
{# Cargar CSS y JavaScript#}
{% bootstrap_javascript jquery=1 %}
{% bootstrap_styles theme='flatly' type='min.css' %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Casa Organica</title>
    <!-- Custom CSS -->
    <link href="{% static "css/thumbnail1-gallery.css"%}" rel="stylesheet">
</head>
<body>
    <div class="col-lg-offset-4 col-lg-4">
        <a href="/" class="navbar-brand">Ingrese sus datos</a>
    </div>
    <div class="container col-lg-offset-4 col-lg-4">
        {% if messages %}
            {% for message in messages %}
                <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock %}
    </div>
    {% block content2 %}
    <form method="post" class="col-lg-offset-4 col-lg-4" >
        {% csrf_token %}
        <div class="form-group">
            <h4 class="form-control2">Usuario:</h4>
            <input type="text" id="username" required="required" name="username" class="form-control input-lg" placeholder="Usuario">
        </div>
        <br>
        <div class="form-group">
            <h4 class="form-control2">Contraseña:</h4>
            <input type="password" id="password" required="required"  name="password" class="form-control input-lg" placeholder="Contraseña">
        </div>
        <br>
        <div class="form-group">
            <button class="btn btn-primary btn-lg btn-block" align="center">Ingresar</button>
            <span class="pull-right">
                <a href="/">Registrarse</a></span>
        </div>
    </form>
    {% endblock %}
</body>
</html>

web/templates/web/registroConsumidor.html
<!DOCTYPE html>
{# Cargar Bootstrap #}
{% load bootstrap3 %}
{% load static %}
{% load staticfiles %}
{# Cargar CSS y JavaScript#}
{% bootstrap_css %}
{% bootstrap_javascript %}
{#% extends 'web/base.html'%#}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Casa Organica</title>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <!-- Bootstrap -->

    <!-- Bootstrap Core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet" type="text/css">

	<!-- Custom CSS -->
    <link href="/static/css/style.css" rel="stylesheet">
	<link href="/static/css/stylesheet.css" rel="stylesheet">
	<link href="/static/css/mb-comingsoon-iceberg.css" rel="stylesheet" />
    <link href="/static/css/thumbnail1-gallery.css" rel="stylesheet">

	<!-- Custom Fonts -->
    <link href="/static/bootstrap/themes/default/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>

</head>
<body>

    <!-- /////////////////////////////////////////Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav nav-justified ">
                    <li>
                        <a class="page-scroll" href="/home">Home</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/web/quienes">¿Quiénes somos?</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/web/nuestros">Nuestros productores</a>
                    </li>
                    <li class="active">
                        <a class="page-scroll" href="">Registrarse</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    <header>
        <div class="carousel-inner">
            <!-- Blog Sidebar Widgets Column -->
            <div class="item active">
                <img src="/static/img/4.jpg" alt="First slide">
                <!-- Static Header -->
                <div class="header-text hidden-xs">
                    <div class="col-md-12 text-center">
                        <div class="col-md-2">
                            <div class="box-item">
                                <img src="/static/img/logo4.png" class="img-circle" width="20" height="20"/>
                            </div>
                        </div>
                        <div class="col-md-10">
                            <h5 class="logo">
                                <div class="and">
                                    Organic Marketplace
                                </div>
                                <br><br>
                                <div class="and">
                                    <h6>¡Haz de nosotros tu estilo de vida!</h6>
                                </div>
                            </h5>
                        </div>
                    </div>
                </div><!-- /header-text -->
            </div>
        </div>
    </header>

    <!-- Blog Sidebar Widgets Column -->
    <div class="col-lg-10" align="center">
        <div class="col-lg-offset-2 col-lg-8">
        {% if messages %}
            {% for message in messages %}
               <div {% if message.tags %} class="alert alert-{{ message.tags }}" id = "id_mensaje"{% endif %}>{{ message }}</div>
            {% endfor %}
        {% endif %}
        <div>
        <form class="form-horizontal" method="post">
                    {% csrf_token %}
            <fieldset>


            <!-- Text input-->
            <div class="form-group">
                <label class="col-md-2 control-label" for="nombres">Nombres:</label>
                <div class="col-md-8">
                    <input id="id_nombres" name="nombres" type="text" placeholder="Nombres" class="form-control input-md" required="" value="{{ consumidor.nombres }}" >
                </div>
            </div>

            <!-- Text input-->
            <div class="form-group">
                <label class="col-md-2 control-label" for="apellidos">Apellidos:</label>
                <div class="col-md-8">
                    <input id="id_apellidos" name="apellidos" type="text" placeholder="Apellidos" class="form-control input-md" required="" value="{{ consumidor.apellidos }}">
                </div>
            </div>

            <!-- Text input-->
            <div class="form-group">
                <label class="col-md-2 control-label" for="correo">Correo:</label>
                <div class="col-md-8">
                  <input id="id_correo" name="correo" type="text" placeholder="Correo" class="form-control input-md" required="" value="{{ consumidor.correo }}">
                </div>
            </div>

            <!-- Text input-->
            <div class="form-group">
              <label class="col-md-2 control-label" for="direccion">Dirección:</label>
              <div class="col-md-8">
                <input id="id_direccion" name="direccion" type="text" placeholder="Dirección" class="form-control input-md" required="" value="{{ consumidor.direccion }}">
              </div>
            </div>

            <!-- Text input-->
            <div class="form-group">
              <label class="col-md-2 control-label" for="usuario">Nombre Usuario:</label>
              <div class="col-md-8">
                <input id="id_usuario" name="usuario" type="text" placeholder="Nombre Usuario" class="form-control input-md" required="" value="{{ consumidor.usuario }}">
              </div>
            </div>

            <!-- List input-->
            <div class="form-group">
              <label class="col-md-2 control-label" for="Ciudad">Ciudad:</label>
              <div class="col-md-8">
                <select id="id_ciudad" name="ciudad" class="form-control" value="{{ consumidor.ciudad }}">
                   {% for entry in ciudades %}
                        <option value="{{ entry.id }}" {% if entry.id == consumidor.ciudad.id  %} selected {% endif %}>{{ entry.nombre }}</option>
                    {% endfor %}
                </select>
              </div>
            </div>

            <!-- Password input-->
            <div class="form-group">
              <label class="col-md-2 control-label" for="password">Contraseña:</label>
              <div class="col-md-8">
                <input id="id_password" name="password" type="password" placeholder="Contraseña" class="form-control input-md" required="" value="{{ consumidorForm.password }}">
              </div>
            </div>

            <!-- Password input-->
            <div class="form-group">
              <label class="col-md-2 control-label" for="password_confirm">Confirmar Contraseña:</label>
              <div class="col-md-8">
                <input id="id_password_confirm" name="password_confirm" type="password" placeholder="Confirmar Contraseña" class="form-control input-md" required="" value="{{ consumidorForm.password_confirm }}">
              </div>
            </div>


                {% buttons %}
                      <button id="id_grabar" class="btn btn-default" type="submit" class="btn btn-primary">Registrarse</button>
                {% endbuttons %}
            </fieldset>
        </form>
    </div>

   <footer>
		<div class="wrap-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-6">
						<div class="copyright">Copyright &copy; Organic Marketplace <br/></div>
                        <ul class="list-inline quicklinks">
							<li><a href="#"><i class="fa fa-twitter-square"></i></a>
							</li>
							<li><a href="#"><i class="fa fa-facebook-square"></i></a>
							</li>
						</ul>
					</div>
					<div class="col-md-6">
						<ul class="list-inline quicklinks">
							<li><a href="#">Privacy Policy</a>
							</li>
							<li><a href="#">Terms of Use</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</footer>
    <!-- jQuery -->
    <script src="/static/js/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="/static/js/bootstrap.min.js"></script>
</body>
</html>

web/templates/web/registroProductor.html
<!DOCTYPE html>
{# Cargar Bootstrap #}
{% load bootstrap3 %}
{% load static %}
{% load staticfiles %}
{# Cargar CSS y JavaScript#}
{% bootstrap_css %}
{% bootstrap_javascript %}
{#% extends 'web/base.html'%#}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Casa Organica</title>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <!-- Bootstrap -->

    <!-- Bootstrap Core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet" type="text/css">

	<!-- Custom CSS -->
    <link href="/static/css/style.css" rel="stylesheet">
	<link href="/static/css/stylesheet.css" rel="stylesheet">
	<link href="/static/css/mb-comingsoon-iceberg.css" rel="stylesheet" />
    <link href="/static/css/thumbnail1-gallery.css" rel="stylesheet">

	<!-- Custom Fonts -->
    <link href="/static/bootstrap/themes/default/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>

</head>
<body>

    <!-- /////////////////////////////////////////Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav nav-justified ">
                    <li>
                        <a class="page-scroll" href="/web/Administrador/homeAdmin">Home</a>
                    </li>
                    <li  class="active">
                        <a class="page-scroll" href="/web/registroProductor">Registrar productores</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="">Administrar productos</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="">Administrar horarios de distribución</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <a class="page-scroll" href="/logout">Cerrar sesión</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    <header>
        <div class="carousel-inner">
            <!-- Blog Sidebar Widgets Column -->
            <div class="item active">
                <img src="/static/img/4.jpg" alt="First slide">
                <!-- Static Header -->
                <div class="header-text hidden-xs">
                    <div class="col-md-12 text-center">
                        <div class="col-md-2">
                            <div class="box-item">
                                <img src="/static/img/logo4.png" class="img-circle" width="20" height="20"/>
                            </div>
                        </div>
                        <div class="col-md-10">
                            <h5 class="logo">
                                <div class="and">
                                    Organic Marketplace
                                </div>
                                <br><br>
                                <div class="and">
                                    <h6>¡Haz de nosotros tu estilo de vida!</h6>
                                </div>
                            </h5>
                        </div>
                    </div>
                </div><!-- /header-text -->
            </div>
        </div>
    </header>

    <!-- Blog Sidebar Widgets Column -->
    <div class="col-lg-10" align="center">
        <div class="col-lg-offset-2 col-lg-8">
        {% if messages %}
            {% for message in messages %}
               <div {% if message.tags %} class="alert alert-{{ message.tags }}" id = "id_mensaje"{% endif %}>{{ message }}</div>
            {% endfor %}
        {% endif %}
        <div>
        <form class="form-horizontal" method="post">
                    {% csrf_token %}
            <fieldset>
                <br>

            <!-- Form Name -->
            <!-- Text input-->
            <div class="form-group">
                <label class="col-md-2 control-label" for="nombres">Nombres:</label>
                <div class="col-md-8">
                    <input id="id_nombres" name="nombres" type="text" placeholder="Nombres" class="form-control input-md" required="" value="{{ productor.nombres }}" >
                </div>
            </div>

            <!-- Text input-->
            <div class="form-group">
                <label class="col-md-2 control-label" for="apellidos">Apellidos:</label>
                <div class="col-md-8">
                    <input id="id_apellidos" name="apellidos" type="text" placeholder="Apellidos" class="form-control input-md" required="" value="{{ productor.apellidos }}">
                </div>
            </div>

            <!-- Text input-->
            <div class="form-group">
                <label class="col-md-2 control-label" for="correo">Correo:</label>
                <div class="col-md-8">
                  <input id="id_correo" name="correo" type="text" placeholder="Correo" class="form-control input-md" required="" value="{{ productor.correo }}">
                </div>
            </div>

            <!-- Text input-->
            <div class="form-group">
              <label class="col-md-2 control-label" for="direccion">Dirección:</label>
              <div class="col-md-8">
                <input id="id_direccion" name="direccion" type="text" placeholder="Dirección" class="form-control input-md" required="" value="{{ productor.direccion }}">
              </div>
            </div>

            <!-- List input-->
            <div class="form-group">
              <label class="col-md-2 control-label" for="Ciudad">Ciudad:</label>
              <div class="col-md-8">
                <select id="id_ciudad" name="ciudad" class="form-control" value="{{ productor.ciudad }}">
                   {% for entry in ciudades %}
                        <option value="{{ entry.id }}" {% if entry.id == productor.ciudad.id  %} selected {% endif %}>{{ entry.nombre }}</option>
                    {% endfor %}
                </select>
              </div>
            </div>



            <!-- Text input-->
            <div class="form-group">
              <label class="col-md-2 control-label" for="usuario">Nombre Usuario:</label>
              <div class="col-md-8">
                <input id="id_usuario" name="usuario" type="text" placeholder="Nombre Usuario" class="form-control input-md" required="" value="{{ productor.usuario }}">
              </div>
            </div>

            <!-- Number input-->
            <div class="form-group">
              <label class="col-md-2 control-label" for="usuario">Telefono:</label>
              <div class="col-md-8">
                <input id="id_telefono" name="telefono" type="number" placeholder="Telefono" class="form-control input-md" required="" value="{{ productor.telefono }}">
              </div>
            </div>

            <!-- Password input-->
            <div class="form-group">
              <label class="col-md-2 control-label" for="password">Contraseña:</label>
              <div class="col-md-8">
                <input id="id_password" name="password" type="password" placeholder="Contraseña" class="form-control input-md" required="" value="{{ productorForm.password }}">
              </div>
            </div>

            <!-- Password input-->
            <div class="form-group">
              <label class="col-md-2 control-label" for="password_confirm">Confirmar Contraseña:</label>
              <div class="col-md-8">
                <input id="id_password_confirm" name="password_confirm" type="password" placeholder="Confirmar Contraseña" class="form-control input-md" required="" value="{{ productorForm.password_confirm }}">
              </div>
            </div>


                {% buttons %}
                      <button id="id_grabar" class="btn btn-default" type="submit" class="btn btn-primary">Registrar</button>
                {% endbuttons %}
            </fieldset>
        </form>
    </div>

   <footer>
		<div class="wrap-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-6">
						<div class="copyright">Copyright &copy; Organic Marketplace <br/></div>
                        <ul class="list-inline quicklinks">
							<li><a href="#"><i class="fa fa-twitter-square"></i></a>
							</li>
							<li><a href="#"><i class="fa fa-facebook-square"></i></a>
							</li>
						</ul>
					</div>
					<div class="col-md-6">
						<ul class="list-inline quicklinks">
							<li><a href="#">Privacy Policy</a>
							</li>
							<li><a href="#">Terms of Use</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</footer>
    <!-- jQuery -->
    <script src="/static/js/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="/static/js/bootstrap.min.js"></script>
</body>
</html>